name: HelloWorldPlugin

author: MW
website:
main: HelloWorldPlugin

commands:
    HelloWorld:
      description: Fotzi!
      usage: /hello

    kill:
      description: Kills the Player!
      usage: /kill


version: 0.1