name: HelloWorldPlugin

author: MW
website:
main: HelloWorldPlugin

commands:
    HelloWorld:
      description: Fotzi!
      usage: /hello

    kill:
      description: Kills the Player!
      usage: /kill

    up:
       description: lifts blocks
       usage: /up

    flyper:
        description: creates flying creeper
        usage: /flyper


version: 0.1

